name: main 

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'archetypes/**'
      - 'myscript/**'
      - 'todo/**'
      - 'todo-done/**'
      - '.gitignore'
      - 'qiniu-sync.py'

jobs:
  deploy: #执行部署Hugo生成静态代码，默认放在gh-pages分支
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.90.1'
          extended: true #不需要extended版本就可以注释

      - name: Build github # 我的Hugo配置baseurl为GitHub Pages路径，使用hugo命令默认为GitHub Pages生成静态网站
        run: hugo

      - name: Deploypage # 部署到GitHub Pages分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: keltoy/keltoy.github.io
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./public
